name: portfolio
description: Nathan Cheshire's flutter portfolio

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0
  json_serializable: ^4.1.4
  http: ^0.13.3
  google_fonts: ^2.1.0
  url_strategy: ^0.2.0
  flutter_arc_text: ^0.5.0
  flutter_screenutil: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_annotation: ^4.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
